title = "ESDStudioProject"
[project_info]
name = "GrandMerchant"
base_directory = "C:\\Users\\benja\\Modding\\Elden Ring\\Projects\\Grand Merchant\\Mod\\GrandMerchant"
game_directory = "F:\\SteamLibrary\\steamapps\\common\\ELDEN RING\\Game"
mod_directory = "C:\\Users\\benja\\Modding\\Elden Ring\\Projects\\Grand Merchant\\Mod"
game = "er"
